# Generated by Django 6.0.5 on 2026-05-05 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_tier', models.CharField(choices=[('1', 'Tier 1 (IIT, NIT, BITS, etc.)'), ('2', 'Tier 2 (Good State Colleges)'), ('3', 'Tier 3 (Local/Private Colleges)')], max_length=1)),
                ('target_role', models.CharField(max_length=100)),
                ('current_skills', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('domain', models.CharField(max_length=100)),
                ('previous_college_tier', models.CharField(choices=[('1', 'Tier 1 (IIT, NIT, BITS, etc.)'), ('2', 'Tier 2 (Good State Colleges)'), ('3', 'Tier 3 (Local/Private Colleges)')], max_length=1)),
                ('internship_status', models.CharField(choices=[('none', 'No initial internship'), ('startup', 'Startup internship'), ('mass', 'Mass recruiter internship')], default='none', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
