# Generated by Django 6.0.5 on 2026-05-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_sessionrequest_status_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
